- hosts: all
  become: yes

  tasks:
    - name: "Deploy the application"
      docker_container:
        image: "kergeodeta/angles:{{ app_version }}"
        name: "angles"
        published_ports:
          - "9000:8080"
        pull: yes
        recreate: yes
        restart_policy: always