- name: "Remove NGINX container"
  docker_container:
    name: "nginx"
    state: "absent"

- name: "Deleting .well-known/acme-challenge directory"
  file:
    path: "{{ challenge_dir }}"
    state: "absent"
    recurse: "yes"

- name: "Deleting NGINX log directory"
  file:
    path: "/var/log/nginx/"
    state: "absent"
    recurse: "yes"

- name: "Deleting NGINX directory"
  file:
    path: "/etc/nginx"
    state: "absent"
    recurse: "yes"