- name: "Create ansible group"
  group:
    name: "ansible"
    state: "present"

- name: "Create ansible user"
  user:
    group: "ansible"
    name: "ansible"
    password: "{{ ansible_agent_password }}"
#    update_password: "on_create"

- name: "Create environment variable which contains ansible password"
  lineinfile:
    path: "/etc/profile"
    line: "export ANSIBLE_PASSWORD='{{ ansible_agent_password }}'"
    create: "yes"
  when: inventory_hostname == "chemaxon_alm"

- name: "Install ansible"
  pip:
    executable: "/usr/bin/pip3"
    name:
      - ansible
    umask: "0022"
  when: inventory_hostname == "chemaxon_alm"